#!/bin/bash
echo "🐱 Testing OpenCode Pets Plugin"
echo "================================"
echo ""
echo "Files in test directory:"
ls -la /tmp/opencode-test/.opencode/plugins/
echo ""
echo "Config:"
cat /tmp/opencode-test/.opencode/tui.json
echo ""
echo "================================"
echo "To test:"
echo "1. cd /tmp/opencode-test"
echo "2. opencode"
echo "3. Look for purple box with '🐱 Pet' in sidebar"
echo "4. Frame counter should increment"
echo ""
echo "If you see the box but no animation:"
echo "- Check terminal is 80+ columns (stty size)"
echo "- Try: export COLORTERM=truecolor"
echo ""
echo "If no box appears:"
echo "- Check OpenCode version: opencode --version"
echo "- Try running opencode from /tmp/opencode-test"
